# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    enabled: '%env(bool:EWZ_RECAPTCHA_ENABLED)%'
    version: 2
    public_key:  '%env(string:EWZ_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(string:EWZ_RECAPTCHA_SECRET)%'
