#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

name="dhil_newn"

mysql -e "DROP DATABASE IF EXISTS $name"
mysql -e "CREATE DATABASE IF NOT EXISTS $name"
mysql -e "CREATE USER IF NOT EXISTS ${name}@localhost"
mysql -e "GRANT ALL ON ${name}.* TO ${name}@localhost"
mysql -e "ALTER USER ${name}@localhost IDENTIFIED BY 'abc123'"
pv newn.sql | mysql "$name";

./bin/console app:import:csv --skip=13 data/2021/works.csv
