<?php

namespace AppBundle\Repository;

/**
 * DateCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
