<?php

namespace AppBundle\Repository;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends \Doctrine\ORM\EntityRepository {

    public function fulltextQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect("MATCH (e.name) AGAINST (:q BOOLEAN) as HIDDEN score");
        $qb->add('where', "MATCH (e.name) AGAINST (:q BOOLEAN) > 0");
        $qb->orderBy('score', 'desc');
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }

}
