<?php

namespace AppBundle\Repository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository {

    public function searchQuery($data) {
        $qb = $this->createQueryBuilder('e');
        if(isset($data['q']) && $data['q']) {
            $qb->addSelect("MATCH (e.label, e.description) AGAINST (:q BOOLEAN) as HIDDEN score");
            $qb->andWhere("MATCH (e.label, e.description) AGAINST (:q BOOLEAN) > 0");
            $qb->setParameter('q', $data['q']);
            $qb->orderBy('score', 'desc');
        }
        if(isset($data['source']) && count($data['source']) > 0) {
            $qb->andWhere('e.subjectSource IN (:sources)');
            $qb->setParameter('sources', $data['source']);
            $qb->orderBy('e.label', 'asc');
        }
        return $qb->getQuery();
    }

}
