<?php

namespace AppBundle\Repository;

/**
 * SubjectSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
