<?php

namespace AppBundle\Repository;

/**
 * WorkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
