
nines_blog:
  resource: '@NinesBlogBundle/Controller'
  prefix: '%router.request_context.base_url%/blog'

nines_editor:
  resource: '@NinesEditorBundle/Controller'
  prefix: '%router.request_context.base_url%/editor'

nines_media:
  resource: '@NinesMediaBundle/Controller'
  prefix: '%router.request_context.base_url%/media'

nines_feedback:
  resource: '@NinesFeedbackBundle/Controller'
  prefix: '%router.request_context.base_url%/feedback'

nines_user:
  resource: '@NinesUserBundle/config/routes.yaml'
  prefix: '%router.request_context.base_url%'

controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: '%router.request_context.base_url%'

kernel:
    resource: ../src/Kernel.php
    type: attribute
    prefix: '%router.request_context.base_url%'